version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: llmops
      POSTGRES_PASSWORD: llmops
      POSTGRES_DB: llmops
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # S3 endpoint
      - "9001:9001" # Web console
    volumes: [miniodata:/data]

volumes:
  pgdata:
  miniodata:
